---
# topic that HandDetector will publish to and MovementControler will Subscribe to.
topic: "/hand_position"
HandDetector:
  # The HandDetector will Publish at the specifiedRate (hertz)
  topicRate: 20
  # The path of the hand model for the Cascade Classifier
  handModelPath: '/home/amal/baxter_ws/src/Lab-Baxter-Reaching-Hand/kinect/haarcascade_hand.xml'
  # The max pixels (in a 640x480 kinect image) the hand can move between frames
  # in order to be classified as the same hand
  maxAllowedHandMotion:
    dx: 75
    dy: 75
  # The distance above the ground (meters) such that if kinect detects a hand
  # at or below this height, it will ignore it
  groundDzThreshold: 0.5
  # The number of seconds of hand positions to average over when getting the
  # average midpoint of the hand
  avgPosDtime: 0.5
  # The number of seconds to average over to get the u, v, point of the most
  # likely hand
  avgHandXYDtime: 1.0
  # If maxIterationsWithNoDifference consecutive images have a difference from
  # the previous frame of < differenceFactor, the HandDetector
  # will assume there is no human in the scene and reset the background.
  # Difference is calculated by the number of pixel channels (RGB) that have
  # by more than differenceThreshold.
  imageDifferenceParams:
    maxIterations: 50
    differenceThreshold: 28
    differenceFactor: 0.007
  # The amount to scale the image by each iteration of cascade classification, and
  # the minNeightbors argument when using cv2's Cascade Classifier
  cascadeClassifierParams:
    scale: 1.3
    minNeighbors: 5
  # When determining the hand height, HAndDetector iterates over the whole average
  # rectangle when the hand, gets the hieght at each point, and takes the max height.
  # These params determine the dx/dy for how many points in the rectangle to Sample
  # when getting the height
  handHeightInterval:
    dx: 10
    dy: 10
MovementController:
  # limb to move
  limb: 'left'
  # speedRatio to limit the velocity of baxter's arm
  speedRatio: 0.3
  # how close (in meters) the end effector has to be to the intended location
  # in order to consider the movement over (or in order to lock the target endpoint)
   # https://github.com/RethinkRobotics/baxter_interface/blob/master/src/baxter_interface/settings.py
  jointThreshold:
    end: 0.008726646
    warning: 0.3
  # rate (hertz) for MovmementController to check whether it has an updated
  # endpoint after it has finished its rajectory
  updateQueryRate: 0.5
  # When baxter's arm wants to move to a position, we slow the movmement by
  # making the target point (1-jointFilteringFactor) times the current
  # point, and only jointFilteringFactor times the target.  This changes
  # depending on it the arm is far or close to the endpoint.
  jointFilteringFactor:
    far: 0.1
    close: 0.5
  # the fixed orientation of the robot end effector
  orientation:
    x: 1.0
    y: 0.0
    z: 0.0
    w: 0.0
